size_name: 50
size_validates: 255
size_validates_min: 8
size_gravatar: 80
user_gravatar: 50
email_def: "tung0602.nhu0311@gmail.com"
max_validate: 140
less_than_5MB: "should be less than 5MB"
size_picture: 5
hour: 2
size_limit_img: 400
